//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ePerfManage.rc
//
#define IDC_BTN_FINDNEXT                2
#define IDD_ABOUTBOX                    100
#define IDS_MAIN_TOOLBAR                101
#define IDD_FORMVIEW                    101
#define IDD_FORMVIEW1                   102
#define IDD_PROPERTYDLGWRDBSTAT_DIALOG  108
#define IDD_PROPERTYDLGRTPOINTBAT_DIALOG 109
#define IDD_DLGVARWITHPORT_DIALOG       110
#define IDD_PROPERTYWRITERDBPROBAT_DIALOG 111
#define IDD_DLGPORTWITHTABLE_DIALOG     112
#define IDD_PROPERTYDLGRDBHISTSERIESBAT_DIALOG 113
#define IDD_DLGVARWITHTABLE_DIALOG      114
#define IDD_PROPERTYDLGSTATPROAVG_DIALOG 115
#define IDD_DLGINPUTOUTPUT_DIALOG       116
#define IDD_PROPERTYWRITERDBSTATBAT_DIALOG 117
#define IDD_PROPERTYDLGRDBSTATSERIESBAT_DIALOG 118
#define IDD_PROPERTYDLGSTATPROENUM_DIALOG 119
#define IDD_PROPERTYDLGSTATELOSTPOWER_DIALOG 120
#define IDD_DLGLOSTPOWERVAR_DIALOG      121
#define IDD_DLGWINDPOWER_DIALOG         122
#define IDD_PROPERTYDLGLIMITLOSTPOWER_DIALOG 123
#define IDD_PROPERTYDLGSTATADD_DIALOG   124
#define IDD_PROPERTYDLGRTDBHISTSERIESBAT_DIALOG 125
#define IDD_PROPERTYWINDPOWERPERF_DIALOG 126
#define IDD_PROPERTYDLGRDBHISTTAGBAT_DIALOG 127
#define IDR_MAINFRAME                   128
#define IDR_EPERFMTYPE                  129
#define IDD_DIALOG_MODERUN_CONCTRL      129
#define IDD_PROPERTYDLGRDBSTATTAGBAT_DIALOG 130
#define IDR_POPUP_TOOLBAR               131
#define IDD_DIALOG_MCTRL_DAY            131
#define IDD_DIALOG_MCTRL_WEEK           132
#define IDD_DIALOG_MCTRL_MONTH          133
#define IDD_PROPERTYDLGSLEEP_DIALOG     134
#define IDB_CLASS_VIEW                  135
#define IDD_DIALOG_MCTRL_DUTY           135
#define IDD_DIALOG_MCTRL_CYCLE          136
#define IDD_DIALOG_CFGSETIME            137
#define IDD_DIALOG_TIME_SETIME          141
#define IDD_DIALOG_SELWEEK              143
#define IDD_DIALOG_SELMONTH             144
#define IDB_SHORTCUTS                   148
#define IDR_MODELFRAME                  154
#define IDD_DIALOG_SELMODEL             156
#define IDD_DIALOG_ADDMODULE            157
#define IDD_DIALOG_ADDMODEL             158
#define IDR_POPUP_LIBBLOCK              159
#define IDD_FORMVIEW_BLOCKLINK          159
#define IDR_POPUP_BLOCK                 160
#define IDD_FORMVIEW_MODELVIEW1         161
#define IDR_POPUP_MODULE                161
#define IDD_FORMVIEW_MODELVIEWDEBUG     161
#define IDD_MODULE_VIEW                 162
#define IDR_TOOLBAR_LINK                164
#define IDR_MAINFRAME1                  165
#define IDD_FORMVIEW_BLOCK              166
#define IDR_MAINFRAME2                  166
#define IDD_DIALOG_RTPOINTS             169
#define IDB_BLOCKS_PAGE                 170
#define IDD_DIALOG_ORDERID              171
#define IDD_DIALOG_MODULEORDER          172
#define IDD_DIALOG_SCHEDULE             173
#define IDD_DIALOG_HISTTIMESPAN         174
#define IDB_HEADER_IMAGES               175
#define IDB_LIST_IMAGES                 176
#define IDD_FORMVIEW_MODULE             176
#define IDD_DIALOG_BLOCKNAME            177
#define IDD_FORMVIEW_WORKSPACE          178
#define IDD_DIALOG_CFGMODULEORDER       179
#define IDD_DIALOG_BCBFIXEDVALUE        180
#define IDD_DIALOG_LINKTO               181
#define IDD_DIALOG_BCBMOMENT            182
#define IDD_DIALOG_BCBREADREAL          183
#define IDD_DIALOG_RTPOINTADV           183
#define IDD_DIALOG_FORMULA_PORT         184
#define IDI_MODUEL_HELP16               185
#define IDD_DIALOG_BCBWRITEREAL         185
#define IDB_INPUT                       185
#define IDB_OUTPUT                      186
#define IDB_INOUT                       187
#define IDD_DIALOG_DEPMODEL             187
#define IDD_DIALOG_BCBREADRELV          188
#define IDB_PORT                        188
#define IDD_DIALOG_PORTDATA             189
#define IDD_DIALOG_BCBWRITERELV         190
#define IDD_DIALOG_FORMUDATA            191
#define IDD_DIALOG_IPPORT               192
#define IDD_DIALOG_ADD                  193
#define IDI_MODUEL_PERFORM16            194
#define IDD_DIALOG_IF                   194
#define IDD_DIALOG_MULT                 195
#define IDD_DIALOG_PEXTSTM              196
#define IDD_DIALOG_MATHFUN              197
#define IDD_DIALOG_CONST                198
#define IDD_DIALOG_COAL                 199
#define IDD_DIALOG_STOP                 200
#define IDD_DIALOG_WASP                 201
#define IDD_DIALOG_LINKFROM             202
#define IDD_DIALOG_ITER_FORMULALIST     203
#define IDD_DIALOG_ITER                 204
#define IDD_DIALOG_FORMULA              205
#define IDD_DIALOG_SINEWAVE             206
#define IDD_DIALOG_CLOCK                207
#define IDD_DIALOG_GAIN                 208
#define D_DIALOG_RTPOINTADV             209
#define IDD_DIALOG_DBPOINTADV           211
#define IDD_DIALOG_WRITERTDB            213
#define IDD_DIALOG_WRITERDB             214
#define IDD_DIALOG_RTPOINT              215
#define IDD_DIALOG_DBPOINT              216
#define IDD_DIALOG_RANDOM               217
#define IDD_DIALOG_PULSE                218
#define IDD_DIALOG_NOTION               219
#define IDD_DIALOG_MODELSYN_NOTE        220
#define IDD_DIALOG_SOURCE_RDB           221
#define IDD_DIALOG_ONE_RDBSOURCE        223
#define IDD_DIALOG_OPTIMALRULE          225
#define IDD_DIALOG_TAB_RULEVAR          226
#define IDD_DIALOG_TAB_OPTRULEFUN       227
#define IDD_DIALOG_RULEOPTFUN           228
#define IDD_DIALOG_SYSVAR               229
#define IDD_DIALOG_STRMERGE             230
#define IDD_DIALOG_STABLEJUDGE          231
#define IDD_DIALOG_HISTSERIESBUFF       232
#define IDD_DIALOG_HISTSERIES           233
#define IDD_DIALOG_DISCRETEVALUE        234
#define IDD_DIALOG_DISCRETETABLE        235
#define IDD_DIALOG_COALK                236
#define IDD_DIALOG_PLCPOINT             237
#define IDD_DIALOG_COAL_FLOW_TAGDATA    238
#define IDD_DIALOG_COALDATA             239
#define IDD_DIALOG_COALDATA1            240
#define IDD_DIALOG_TAB_COALOUT          243
#define IDD_DIALOG_TAB_COALKTAG         244
#define IDD_DIALOG_STAT                 245
#define IDD_DIALOG_WRITEPLC             246
#define IDD_DIALOG_STATVAR_SEL          247
#define IDD_DIALOG_DEL_MODEL            248
#define IDD_DIALOG_TIME                 250
#define IDD_DIALOG_TASK_STARTUP_TIME    252
#define IDD_DIALOG_LOCALRUNSETTING      253
#define IDD_PROPDLG_RULERUN             254
#define IDD_DIALOG_RULE_FBLIST          255
#define IDD_DIALOG_RULE_FBVAR           256
#define IDD_CFG_FIND_BLOCK              257
#define IDD_TAB_FINDBLOCK               258
#define IDD_DIG_TAB_FINDBLOCK           259
#define IDD_DIALOG_STRMAPTONUM          261
#define IDD_DIALOG_STRTONUMDATA         262
#define IDD_DIALOG_RDBFIELD             263
#define IDD_DIALOG_WAVEINTERVAL         264
#define IDD_DIALOG_DISDATA              265
#define IDD_DIALOG_SAWTOOTH             266
#define IDD_DIALOG_NUM_TO_STR           267
#define IDD_DLGPROGRESS                 268
#define IDD_DIALOG_MRENAME              269
#define IDD_DIALOG_STAT_AVG             270
#define IDB_BITMAP1                     271
#define IDD_DIALOG_VARDATA_REQ          272
#define IDD_DIALOG_STAT_ACCUM           275
#define IDD_DIALOG_VARDATA_BASE         276
#define IDD_DIALOG_STAT_ENUM            277
#define IDD_DIALOG_VAR_SEVALUE          279
#define IDD_DIALOG_INTEGRATE            281
#define IDD_DIALOG_AVGSERIES            282
#define IDI_ICON1                       282
#define IDD_DIALOG_TIME_OFFSET          283
#define IDD_DIALOG_STAT_ADV             285
#define IDD_DIALOG_SUMSERIES            286
#define IDC_CURSOR1                     291
#define IDD_DIALOG_PROCESSTOSTATIS      292
#define IDD_DIALOG_STATISTOPROCESS      293
#define IDD_DIALOG_BACKCALC             294
#define IDD_DIALOG_LINKTOPROBAT         295
#define IDD_DIALOG_PROBATINPUT          296
#define IDD_DIALOG_LINKFROMPROBAT       297
#define IDD_DIALOG_PROBATOUTPUT         298
#define IDD_DIALOG_DBLASTPOINT          299
#define IDD_PROPERTYWINDSTANDPOWERPERF_DIALOG 300
#define IDD_PROPERTYSTANDWINDPOWERPERF_DIALOG 301
#define IDD_DIALOG_UtiliRatePlg         302
#define IDD_PROPERTYDLGSTATPROENUMPARAEXT_DIALOG 303
#define IDD_PROPERTYWINDPOWERPERFPARAEXT_DIALOG 306
#define IDD_PROPERTYDLGSTATELOSTPOWERPARAEXT_DIALOG 307
#define IDD_PROPERTYDLGLIMITLOSTPOWERPARAEXT_DIALOG 308
#define IDD_DIALOG_RTDBHistSeriesBat    309
#define IDC_BUTTON_CANCLE               1001
#define IDC_BUTTON_APPLY                1002
#define IDC_BUTTON_OK                   1003
#define IDC_COMBO_TASKTYPE              1004
#define IDC_CHECK_ETIME                 1007
#define IDC_Comb                        1007
#define IDC_DATETIMEPICKER_SDATE        1008
#define IDC_EDIT7                       1008
#define IDC_DATETIMEPICKER_STIME        1009
#define IDC_EDIT8                       1009
#define IDC_DATETIMEPICKER_EDATE        1010
#define IDC_DATETIMEPICKER_ETIME        1011
#define IDC_TREE_MONTH                  1018
#define IDC_BUTTON4                     1019
#define IDC_COMBO_UNIT                  1020
#define IDC_BUTTON_SETRUNABSTIME        1022
#define IDC_BUTTON_SETRUNDATATIME       1023
#define IDC_STATIC_CTRLDLG              1024
#define IDC_STATIC_TASKLIFE             1025
#define IDC_EDIT_ESECOND                1026
#define IDC_STATIC_CALCDATASETIME       1026
#define IDC_EDIT_EDAY                   1027
#define IDC_RADIO_SE                    1028
#define IDC_EDIT_EWEEK                  1028
#define IDC_RADIO_CURRENT               1029
#define IDC_EDIT_EMONTH                 1029
#define IDC_EDIT_CYCLELENGTH            1030
#define IDC_EDIT_EDUTY                  1031
#define IDC_RADIO01                     1038
#define IDC_RADIO02                     1039
#define IDC_RADIO03                     1040
#define IDC_RADIO9                      1040
#define IDC_COMPANY_URL                 1041
#define IDC_RADIO04                     1041
#define IDC_EDIT1                       1042
#define IDC_RADIO05                     1042
#define IDC_RADIO10                     1042
#define IDC_BUTTON_CONFIRM              1043
#define IDC_EDIT_NAME                   1043
#define IDC_EDIT4                       1043
#define IDC_EDIT_SSECOND                1043
#define IDC_STATIC_TOOL                 1044
#define IDC_EDIT3                       1044
#define IDC_EDIT_BDAY                   1044
#define IDC_EDIT_UNIT                   1044
#define IDC_EDIT9                       1044
#define IDC_RADIO16                     1044
#define IDC_LIST1                       1045
#define IDC_LIST_MODULE                 1045
#define IDC_EDIT6                       1045
#define IDC_EDIT_VALUE                  1045
#define IDC_EDIT_SNAP_T                 1045
#define IDC_EDIT_UPORDOWM               1045
#define IDC_EDIT_DESP                   1046
#define IDC_EDIT_SDAY                   1046
#define IDC_LIST4                       1046
#define IDC_EDIT_MIN_SPEED              1046
#define IDC_LIST2                       1047
#define IDC_LIST_BLOCKS                 1047
#define IDC_EDIT_SWEEK                  1047
#define IDC_EDIT_SHOUR                  1047
#define IDC_EDIT_MAXSPEED               1047
#define IDC_BUTTON_LINK                 1048
#define IDC_EDIT_SMONTH                 1048
#define IDC_EDIT_SNAP_TIME              1048
#define IDC_EDIT_SNAP_CON_T             1048
#define IDC_LIST3                       1049
#define IDC_BUTTON_AHEAD                1049
#define IDC_EDIT_SDUTY                  1049
#define IDC_EDIT_WEEK                   1049
#define IDC_BUTTON_LINK2                1050
#define IDC_DATETIMEPICKER_SDTIME       1050
#define IDC_COMBO1                      1051
#define IDC_COMBO_MODULE                1051
#define IDC_COMBO_OUTMETHOD             1051
#define IDC_COMBO_INTERVALUNIT          1051
#define IDC_COMBO_FUNDESP               1051
#define IDC_COMBO_TYPE                  1051
#define IDC_COMBO_MODESOURCE            1051
#define IDC_COMBO_DBSEL                 1051
#define IDC_DATETIMEPICKER_SHTIME       1051
#define IDC_LIST_BLOCK                  1052
#define IDC_BUTTON_REAR                 1052
#define IDC_COMBO_INTERVALMODE          1052
#define IDC_COMBO_TYPE2                 1052
#define IDC_COMBO_DBSEL2                1052
#define IDC_COMBO2                      1052
#define IDC_EDIT_SYEAR                  1052
#define IDC_PROPLIST_LOCATION           1053
#define IDC_COMBO_TYPE3                 1053
#define IDC_LIST_BLOKIO                 1054
#define IDC_COMBO_TYPE4                 1054
#define IDC_GRID_LOCATION               1055
#define IDC_STATIC_GRID                 1055
#define IDC_COMBO_TYPE5                 1055
#define IDC_COMBO_EWEEK                 1055
#define IDC_DATETIMEPICKER_EDTIME       1056
#define IDC_STATIC_LINKTOOLBAR          1057
#define IDC_RADIO11                     1057
#define IDC_RADIO12                     1058
#define IDC_RADIO13                     1059
#define IDC_EDIT_TAG1                   1060
#define IDC_RADIO14                     1060
#define IDC_EDIT_TAG2                   1061
#define IDC_RADIO15                     1061
#define IDC_EDIT_TAG3                   1062
#define IDC_DATETIMEPICKER_EWTIME       1062
#define IDC_EDIT_TAG4                   1063
#define IDC_COMBO_EMONTH                1063
#define IDC_EDIT_TAG5                   1064
#define IDC_DATETIMEPICKER_EMTIME       1064
#define IDC_EDIT_TAG6                   1065
#define IDC_COMBO_EDUTY                 1065
#define IDC_EDIT_TAGDESP                1066
#define IDC_DATETIMEPICKER_SWTIME       1066
#define IDC_EDIT_CONSTWHENBAD           1067
#define IDC_DATETIMEPICKER_SMTIME       1067
#define IDC_EDIT_FORCEVALUE             1068
#define IDC_COMBO_SWEEK                 1068
#define IDC_CHECK_FORCEOUTPUT           1069
#define IDC_COMBO_SMONTH                1069
#define IDC_CHECK_LIMIT                 1070
#define IDC_EDIT_ORDER                  1070
#define IDC_COMBO_SDUTY                 1070
#define IDC_COMBO_SWEEK_DAY             1070
#define IDC_EDIT_HIGHLIMIT              1071
#define IDC_BUTTON_UP                   1071
#define IDC_BUTTON_ADD                  1071
#define IDC_COMBO_SYEAR_M               1071
#define IDC_BUTTON_DOWN                 1072
#define IDC_DATETIMEPICKER_STARTDATE    1072
#define IDC_BUTTON_EDIT                 1072
#define IDC_DATETIMEPICKER_SYTIME       1072
#define IDC_EDIT_LOWLIMIT               1073
#define IDC_DATETIMEPICKER_STARTTIME    1073
#define IDC_BUTTON_DEL                  1073
#define IDC_COMBO_SYEAR_D               1073
#define IDC_DATETIMEPICKER_ENDDATE      1074
#define IDC_EDIT_COUNT                  1074
#define IDC_BUTTON_ADD2                 1074
#define IDC_DATETIMEPICKER_ENDTTIME     1075
#define IDC_DATETIMEPICKER_TIME         1075
#define IDC_BUTTON_EDIT2                1075
#define IDC_SPIN1                       1076
#define IDC_BTNSELWEEK                  1076
#define IDC_BUTTON_DEL2                 1076
#define IDC_EDIT_INTERVAL_VALUE         1077
#define IDC_TREE_WEEK                   1077
#define IDC_EDIT_FIXED                  1078
#define IDC_GRIDCTRL                    1078
#define IDC_CHECK1                      1078
#define IDC_DATETIMEPICKER1             1079
#define IDC_CHECK2                      1079
#define IDC_BUTTON_MOVEUP               1079
#define IDC_DATETIMEPICKER_DATA         1079
#define IDC_DATETIMEPICKER2             1080
#define IDC_RADIO1                      1080
#define IDC_CHECK3                      1080
#define IDC_BUTTON_MOVEDOWN             1080
#define IDC_RADIO2                      1081
#define IDC_CHECK4                      1081
#define IDC_EDIT_TAG                    1082
#define IDC_BTNSELMONTH                 1082
#define IDC_CHECK5                      1082
#define IDC_EDIT_IP                     1082
#define IDC_RADIO7                      1082
#define IDC_EDIT_STATUS                 1083
#define IDC_CHECK6                      1083
#define IDC_COMBO_DAY                   1083
#define IDC_EDIT_PORT                   1083
#define IDC_RADIO8                      1083
#define IDC_EDIT_OFFSET                 1084
#define IDC_RADIO3                      1084
#define IDC_EDIT2                       1084
#define IDC_CHECK7                      1084
#define IDC_STATIC_MDAY                 1084
#define IDC_EDIT_INPUT                  1084
#define IDC_RADIO4                      1085
#define IDC_EDIT5                       1085
#define IDC_CHECK8                      1085
#define IDC_STATIC_HAO                  1085
#define IDC_EDIT_CONST                  1085
#define IDC_EDIT_TIMELENGTH             1085
#define IDC_EDIT_OFFSET2                1086
#define IDC_BtnAddFormula               1086
#define IDC_CHECK9                      1086
#define IDC_STATIC_TIME                 1086
#define IDC_CHECK_TIME                  1086
#define IDC_EDIT_RDBPASS                1086
#define IDC_CHECK10                     1087
#define IDC_STATIC_DUTYNUM              1087
#define IDC_CHECK_SETIME                1087
#define IDC_EDIT_USERNAME               1087
#define IDC_BtnUpFormula                1088
#define IDC_CHECK11                     1088
#define IDC_STATIC_DUTYSORE             1088
#define IDC_EDIT_FILENAME               1088
#define IDC_BtnDownFormula              1089
#define IDC_CHECK12                     1089
#define IDC_COMBO_DUTYSORE              1089
#define IDC_STATIC_INPUT                1089
#define IDC_COMBO_DUTYNUM               1090
#define IDC_EDIT_GAIN                   1090
#define IDC_RADIO_BACK                  1091
#define IDC_BtnDelFormula               1092
#define IDC_RADIO_FORWARD               1092
#define IDC_EDIT_DBTABLE_NAME           1093
#define IDC_EDIT_DBTYPE                 1094
#define IDC_TABLIST                     1095
#define IDC_RADIO5                      1095
#define IDC_BtnAddPort                  1096
#define IDC_RADIO6                      1096
#define IDC_BtnDelPort                  1097
#define IDC_BtnUpPort                   1098
#define IDC_BtnDownPort                 1099
#define IDC_BUTTON13                    1100
#define IDC_BtnEditFormula              1101
#define IDC_TREE_PORTPAR                1102
#define IDC_LIST_FORMULA                1103
#define IDC_EDIT_VAR                    1104
#define IDC_EDIT_FORMULA                1105
#define IDC_LIST                        1106
#define IDC_BUTTON_TESTFORMULA          1106
#define IDC_BtnEditPort                 1107
#define IDC_BUTTON_UPRESTAR             1107
#define IDC_EDITNAME                    1108
#define IDC_TABLIST2                    1109
#define IDC_CHECK_BEIGNOREPLOSS         1109
#define IDC_COMBO_TYPE1                 1110
#define IDC_BUTTON_APP                  1110
#define IDC_RADIOMS1                    1111
#define IDC_RADIOMS2                    1112
#define IDC_CHECK_FIXMF                 1113
#define IDC_EDIT_SOURCENAME             1113
#define IDC_RADIOS1                     1114
#define IDC_EDIT_RDBNAME                1114
#define IDC_RADIOS2                     1115
#define IDC_COMBO_UNITSEL               1115
#define IDC_BUTTON_SEARCH               1115
#define IDC_RADIOS3                     1116
#define IDC_COMBO_RULELIST              1116
#define IDC_InputNum                    1116
#define IDC_RADIOS4                     1117
#define IDC_BUTTON1                     1117
#define IDC_EDIT_SNAPSTEP               1117
#define IDC_RADIOAshAr1                 1118
#define IDC_BUTTON_VARSEL               1118
#define IDC_EDIT_POINTNAME              1118
#define IDC_BUTTON_EDIT_FLOW            1118
#define IDC_BUTTON_OUTPUT               1118
#define IDC_RADIOAshAr2                 1119
#define IDC_EDIT_BUFFTIME               1119
#define IDC_BUTTON_DEL_FLOW             1119
#define IDC_BUTTON_OUTPUT2              1119
#define IDC_RADIOAshAr3                 1120
#define IDC_EDIT_OUTPUTTIME             1120
#define IDC_RADIOAshAr4                 1121
#define IDC_EDIT_CGID                   1121
#define IDC_EDIT_F1                     1121
#define IDC_RADIOLwCoalAr1              1122
#define IDC_EDIT_FUNFORMULA             1122
#define IDC_EDIT_F2                     1122
#define IDC_RADIOLwCoalAr2              1123
#define IDC_TREE_GROUP                  1123
#define IDC_EDIT_DOWN1                  1123
#define IDC_RADIOLwCoalAr3              1124
#define IDC_LIST_VAR                    1124
#define IDC_EDIT_DOWN2                  1124
#define IDC_RADIOLwCoalAr4              1125
#define IDC_RADIOH1                     1126
#define IDC_LIST_SELVAR                 1126
#define IDC_RADIOH2                     1127
#define IDC_EDIT_FDAY                   1127
#define IDC_RADIOH3                     1128
#define IDC_EDIT_STEP                   1128
#define IDC_RADIOH4                     1129
#define IDC_COMBO_STEPUNIT              1129
#define IDC_RADIOH5                     1130
#define IDC_EDIT_TAGNAME_POWER          1130
#define IDC_RADIOH6                     1131
#define IDC_EDIT_POWER_UNIT             1131
#define IDC_EDIT_MF                     1132
#define IDC_BUTTON_ADD_FLOW             1132
#define IDC_STATIC_BLOCKDISP            1133
#define IDC_LIST_FLOW                   1133
#define IDC_EDIT_FUNNAME                1134
#define IDC_EDIT_TAGNAME                1134
#define IDC_EDIT_DAY                    1135
#define IDC_EDIT_THRESHOLD              1136
#define IDC_STATIC1                     1138
#define IDC_BUTTON_VAR_SEL              1138
#define IDC_RADIOSE1                    1139
#define IDC_RADIOSE2                    1140
#define IDC_RADIOSE3                    1141
#define IDC_EDIT_SET                    1142
#define IDC_STATIC_BLOCK_DESP           1143
#define IDC_CHECK_UP                    1144
#define IDC_STATIC_BLOCK_DESP2          1144
#define IDC_CHECK_DOWN                  1145
#define IDC_EDIT_VALUE_UP               1146
#define IDC_EDIT_VALUE_DOWN             1147
#define IDC_EDIT_CODE_UP                1148
#define IDC_EDIT_CODE_DOWN              1149
#define IDC_STATIC_ENUM                 1150
#define IDC_STATIC_CODE_UP              1151
#define IDC_STATIC_CODE_DOWN            1152
#define IDC_BUTTON_CLOSE                1153
#define IDC_COMBO_QUERYTYPE             1154
#define IDC_COMBO_MODE                  1155
#define IDC_COMBO_CYCEL                 1156
#define IDC_BUTTON_ALLONETIME           1157
#define IDC_COMBO_INTERVAL              1158
#define IDC_BUTTON_CONSTRING            1158
#define IDC_EDIT_CONSTRING              1159
#define IDC_EDIT_RULEDBNAME             1160
#define IDC_BUTTON_CONSTRING2           1161
#define IDC_BUTTON_SEL_RULEID           1161
#define IDC_EDIT_RULEDBDESP             1162
#define IDC_TAB1                        1163
#define IDC_STATIC2                     1165
#define IDC_BTN_FINDALL                 1166
#define IDC_BTN_REPLACE                 1167
#define IDC_EDIT_FIND                   1167
#define IDC_BTN_REPLACEALL              1168
#define IDC_EDIT_REPLACE                1168
#define IDC_COMBO_RANGE                 1169
#define IDC_STATIC_REPLACE              1170
#define IDC_CHECK_ALLSAME               1171
#define IDC_BUTTON_QUERY                1172
#define IDC_BUTTON_RDBFIELD             1173
#define IDC_CHECK_ENABLE_PORT           1174
#define IDC_EDIT_TIME                   1176
#define IDC_EDIT_STATE                  1177
#define IDC_CHECK_CALC_NOSTABLE         1178
#define IDC_EDIT_SPAN_INT_PERCENT       1179
#define IDC_EDIT_SPAN_KEEP_TIME         1180
#define IDC_EDIT_DIS_VALUE              1181
#define IDC_EDIT_SVALUE                 1182
#define IDC_EDIT_EVALUE                 1183
#define IDC_EDIT_S_WIDTH                1184
#define IDC_EDIT_S_STEP                 1185
#define IDC_EDIT_MAX                    1186
#define IDC_EDIT_MIN                    1187
#define IDC_PROGRESS1                   1188
#define IDC_EDIT_VARNAME                1190
#define IDC_EDIT_STR_UNIT               1191
#define IDC_COMBO_REQ_TYPE              1192
#define IDC_BUTTON_INPUT                1193
#define IDC_COMBO_STAT_TYPE             1193
#define IDC_EDIT_OUTNAME                1193
#define IDC_EDIT_GAINS                  1194
#define IDC_EDIT_OUTNAME2               1194
#define IDC_COMBO_CON_FUN1              1194
#define IDC_BUTTON_INPUT2               1194
#define IDC_BUTTON_ADV                  1195
#define IDC_CHECK_TIME_MINT             1196
#define IDC_EDIT_CON_VALUE1             1196
#define IDC_CHECK_MAX_VALUE             1197
#define IDC_COMBO_CON_FUN2              1197
#define IDC_CHECK_MIN_VALUE             1198
#define IDC_EDIT_CON_VALUE2             1198
#define IDC_CHECK_COUNT                 1199
#define IDC_CHECK_CON                   1199
#define IDC_CHECK_STAT                  1200
#define IDC_COMBO_CON_REQ_TYPE          1200
#define IDC_EDIT_CON_UNIT               1201
#define IDC_EDIT_CON_DESP               1202
#define IDC_EDIT_CON_VARNAME            1203
#define IDC_EDIT_PORTNAME               1204
#define IDC_COMBO_CON_FUN3              1205
#define IDC_EDIT_TABLENAME              1205
#define IDC_CHECK_ONLY_SAVE             1206
#define IDC_EDIT_SAVE_SEC               1207
#define IDC_EDIT_OUTPUT                 1208
#define IDC_STATIC_DESP                 1209
#define IDC_EDIT_RANG_LEFT              1210
#define IDC_EDIT_RANG_RIGHT             1211
#define IDC_EDIT_STAT_TYPE              1212
#define IDC_COMBO_FUN_TYPE              1213
#define IDC_EDIT_IVALID                 1215
#define IDC_EDIT_WIND                   1216
#define IDC_EDIT_IVALID_Max             1216
#define IDC_EDIT_POWER                  1217
#define IDC_EDIT_VALID                  1218
#define IDC_EDIT_SPAN                   1219
#define IDC_EDIT_TABLE_NAME             1220
#define IDC_EDIT_Turbine                1221
#define IDC_EDIT_Product_MIN            1222
#define IDC_EDIT_LIMIT                  1223
#define IDC_EDIT_Product_MAX            1224
#define IDC_EDIT_NEAR_SEC               1224
#define IDC_EDIT_SLEEP                  1225
#define IDC_EDIT_PSTAT_TYPE             1226
#define IDC_RADIO_ISTIME                1227
#define IDC_RADIO_IETIME                1228
#define IDC_RADIO_IINSERTTIME           1229
#define IDC_EDIT_PROC_TYPE              1230
#define IDC_EDIT_BACKCALC               1231
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_OUTLOOKBAR              32817
#define ID_SHORTCUT_1                   32818
#define ID_SHORTCUT_2                   32819
#define ID_SHORTCUT_3                   32820
#define ID_SHORTCUT_4                   32821
#define ID_SHORTCUTS_PANE_1             32824
#define ID_SHORTCUTS_PANE_2             32825
#define ID_SHORTCUTS_TREE               32826
#define ID_VIEW_OUTPUT                  32827
#define ID_SHORTCUTS_TREE_1             32828
#define ID_SHORTCUTS_TREE_2             32829
#define ID_RUN_RT_START                 32834
#define ID_RUN_RT_STOP                  32835
#define ID_RUN_HIST_SELTIME             32836
#define ID_RUN_STEP_1                   32837
#define ID_RUN_STEP_2                   32838
#define ID_RUN_HIST_STEP2               32839
#define ID_RUN_HIST_STEP3               32840
#define ID_RUN_HIST_STEP4               32841
#define ID_RUN_STEP_3                   32842
#define ID_RUN_STEP_4                   32843
#define ID_RUN_STEP_5                   32844
#define ID_FILE_OPEN_MODEL              32845
#define ID_CFG_ADD_MODULE               32846
#define ID_CFG_ADD_BLOCK                32847
#define ID_FILE_NEWMODEL                32848
#define ID_FILE_MODEL_CLOSE             32850
#define ID_FILE_MODEL_NEW               32853
#define ID_MODEL_MENU                   32854
#define ID_VIEW_MAIL_TOOLBAR            32855
#define ID_LIBBLOCK_PROP                32856
#define ID_LIBBLOCK_DEL                 32857
#define ID_MODULE_ADDBLOCK              32857
#define ID_LIBBLOCK_OPEN                32858
#define ID_MODULE_PROP                  32858
#define ID_LIBBLOCK_ADD                 32859
#define ID_FVLINK_LINK                  32859
#define ID_VIEW_CLASS                   32860
#define ID_FVLINK_DISLINK               32860
#define ID_VIEW_MODELCLASS              32861
#define IDC_MODELTREE                   32862
#define IDC_GRID_BLOCK                  32863
#define IDC_GRID_BLOCK1                 32864
#define IDC_MANAGETREE                  32865
#define ID_VIEW_CLOSEPAGE               32867
#define ID_FILE_SAVEMODEL               32868
#define ID_FILE_SAVE_MODULE             32869
#define ID_RUN_COMPILE                  32870
#define ID_CFG_ORDERSHOW                32872
#define ID_RUN_DEBUG                    32873
#define ID_VIEW_CLOSEALLPAGE            32874
#define ID_CFG_MODULEORDER              32875
#define ID_BUTTON32877                  32877
#define ID_RUN_EXCUTE                   32882
#define ID_RUN_STOPEXECUTE              32886
#define ID_RUN_EXECUTEINWINDOW          32888
#define ID_RUN_STOPEXECUTE_INWINDOW     32889
#define ID_MAG_RUN                      32890
#define ID_MAG_STOP                     32891
#define ID_MAG_PAUSE                    32892
#define ID_MAG_RESUME                   32893
#define ID_FILE_UPLOADMODEL             32894
#define ID_MAG_REFRESHWS                32895
#define ID_MAG_PORTVALUESHOW            32896
#define ID_CFG_MODERUNCONTROL           32897
#define ID_DEP_MODEL                    32898
#define ID_MAG_STARTGETLOG              32899
#define IDC_LIST_DEBUG                  32900
#define ID_MAG_ENDGETLOG                32900
#define ID_VIEW_MODELMANAGECLASS        32901
#define ID_MAG_REFRESHWS_START          32901
#define ID_MAG_REFRESHWS_END            32902
#define ID_MAG_MODELSYN                 32903
#define ID_DEBUG_GO                     32904
#define ID_DEBUG_SINGLESTEP             32905
#define ID_DEBUG_GOTOLINE               32906
#define ID_DEBUG_CANCEL                 32907
#define ID_MENUITEM32909                32909
#define ID_TOOL_SOURCE_RDB              32910
#define ID_FILE_DEL_MODEL               32918
#define ID_CFG_DEL_MODULE               32919
#define ID_FILE_CLOSEMODLE              32920
#define ID_MENUITEM32921                32921
#define ID_RUN_LOCALPARA                32922
#define ID_RUN_LOCAL_START              32923
#define ID_RUN_LOCAL_STOP               32924
#define ID_CFG_FIND_BLOCK               32925
#define ID_CFG_SET_BLOCK_CALID          32926
#define ID_FILE_OPEN_ALLMODULE          32927
#define ID_FILE_CLOSE_ALLMODULE         32928
#define ID_MODULE_RENAME                32929

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         32930
#define _APS_NEXT_CONTROL_VALUE         1232
#define _APS_NEXT_SYMED_VALUE           135
#endif
#endif
